from __future__ import annotations

import copy
import os
from pathlib import Path

from . import proxy
from .config import RUNTIME_DIR, save_config
from .themes import RADIUS_VALUES, accent_scale, dark_scale, lighten, rgb, css_rgb, css_rgb_csv
from .utils import CommandError, run

SUBPAGE_CONTAINER = 'remnawave-subscription-page'
SUBPAGE_UPSTREAM = 'remnawave-subscription-page:3010'
SUBPAGE_CUSTOM_TARGET = 'remnawave-customizer-proxy:3101'
SUBPAGE_TARGETS = (
    SUBPAGE_UPSTREAM,
    '127.0.0.1:3010',
    'localhost:3010',
)

DEFAULT_SUBPAGE = {
    'enabled': False,
    'mode': 'custom',
    'preset': 'remnawave',
    'accent': [6, 182, 212],
    'background': [22, 27, 35],
    'surface': [33, 38, 45],
    'radius': 'medium',
    'route': {},
}


def ensure_config(config: dict) -> dict:
    current = config.get('subpage')
    if not isinstance(current, dict):
        current = {}
        config['subpage'] = current
    for key, value in DEFAULT_SUBPAGE.items():
        if key not in current:
            current[key] = copy.deepcopy(value)
    route = current.get('route')
    if not isinstance(route, dict):
        current['route'] = {}
    return current


def local_status() -> tuple[bool, str]:
    code, out, _ = run(
        f"docker inspect -f '{{{{.State.Running}}}}' {SUBPAGE_CONTAINER}",
        timeout=15,
    )
    if code != 0:
        return False, 'container not found'
    if out.strip().lower() != 'true':
        return False, 'container is not running'

    code, out, _ = run(
        f"docker inspect -f '{{{{json .NetworkSettings.Networks}}}}' {SUBPAGE_CONTAINER}",
        timeout=15,
    )
    if code == 0 and 'remnawave-network' not in out:
        return False, 'container is not connected to remnawave-network'
    return True, ''


def is_local() -> bool:
    return local_status()[0]


def _radius_vars(radius_key: str) -> dict[str, int]:
    base = RADIUS_VALUES.get(radius_key, 10)
    return {
        'xs': max(0, base - 6),
        'sm': max(0, base - 3),
        'md': base,
        'lg': base + 4 if base else 0,
        'xl': base + 8 if base else 0,
    }


def render_css(theme: dict) -> str:
    accent = rgb(theme['accent'])
    background = rgb(theme['background'])
    surface = rgb(theme['surface'])
    accents = accent_scale(accent)
    darks = dark_scale(background, surface)
    border = darks[4]
    hover = lighten(surface, 0.045)
    radius_key = str(theme.get('radius', 'medium'))
    radii = _radius_vars(radius_key)

    lines = [
        '/* Generated by Remnawave Customizer for local Subscription Page. */',
        ':root, [data-mantine-color-scheme="dark"] {',
        f'  --rwc-sub-background: {css_rgb(background)};',
        f'  --rwc-sub-surface: {css_rgb(surface)};',
        f'  --rwc-sub-surface-hover: {css_rgb(hover)};',
        f'  --rwc-sub-border: {css_rgb(border)};',
        f'  --rwc-sub-accent: {css_rgb(accent)};',
        f'  --rwc-sub-accent-rgb: {css_rgb_csv(accent)};',
        f'  --mantine-color-body: {css_rgb(background)} !important;',
        '  --mantine-color-anchor: var(--rwc-sub-accent) !important;',
        '  --mantine-color-default: var(--mantine-color-dark-6) !important;',
        '  --mantine-color-default-hover: var(--rwc-sub-surface-hover) !important;',
        '  --mantine-color-default-border: var(--rwc-sub-border) !important;',
        f'  --mantine-radius-default: {radii["md"]}px !important;',
    ]
    for key, value in radii.items():
        lines.append(f'  --mantine-radius-{key}: {value}px !important;')
    for i, value in enumerate(darks):
        lines.append(f'  --mantine-color-dark-{i}: {css_rgb(value)} !important;')

    # The Subscription Page uses cyan as its primary accent, but also hardcodes
    # blue/violet for decorative UI. Keep semantic green/red/orange/yellow intact.
    for palette in ('cyan', 'blue', 'indigo', 'violet'):
        for i, value in enumerate(accents):
            lines.append(f'  --mantine-color-{palette}-{i}: {css_rgb(value)} !important;')
        lines.extend([
            f'  --mantine-color-{palette}-filled: {css_rgb(accents[8])} !important;',
            f'  --mantine-color-{palette}-filled-hover: {css_rgb(accents[9])} !important;',
            f'  --mantine-color-{palette}-light: rgba(var(--rwc-sub-accent-rgb), 0.14) !important;',
            f'  --mantine-color-{palette}-light-hover: rgba(var(--rwc-sub-accent-rgb), 0.20) !important;',
            f'  --mantine-color-{palette}-light-color: {css_rgb(accents[4])} !important;',
            f'  --mantine-color-{palette}-outline: {css_rgb(accents[7])} !important;',
            f'  --mantine-color-{palette}-outline-hover: rgba(var(--rwc-sub-accent-rgb), 0.10) !important;',
        ])
    lines.append('}')

    lines.extend([
        '',
        'html, body {',
        '  background-color: var(--rwc-sub-background) !important;',
        '  background-image:',
        '    linear-gradient(to right, rgba(var(--rwc-sub-accent-rgb), 0.035) 1px, transparent 1px),',
        '    linear-gradient(to bottom, rgba(var(--rwc-sub-accent-rgb), 0.035) 1px, transparent 1px) !important;',
        '}',
        '.animated-background {',
        '  background:',
        '    radial-gradient(ellipse 60% 40% at 25% 40%, rgba(var(--rwc-sub-accent-rgb), 0.075), transparent 50%),',
        '    radial-gradient(ellipse 50% 50% at 85% 85%, rgba(var(--rwc-sub-accent-rgb), 0.055), transparent 50%) !important;',
        '}',
        '.header-wrapper {',
        '  background: color-mix(in srgb, var(--rwc-sub-background) 82%, transparent) !important;',
        '  border-bottom-color: rgba(var(--rwc-sub-accent-rgb), 0.08) !important;',
        '}',
        '.logo-text-highlight { color: var(--rwc-sub-accent) !important; }',
        '.info-card-cyan, .info-card-violet, .info-card-blue {',
        '  background: linear-gradient(135deg, rgba(var(--rwc-sub-accent-rgb), 0.10), rgba(var(--rwc-sub-accent-rgb), 0.045)) !important;',
        '  border-color: rgba(var(--rwc-sub-accent-rgb), 0.20) !important;',
        '}',
        '.mantine-ActionIcon-root[style*="mantine-color-cyan"],',
        '.mantine-ActionIcon-root[style*="mantine-color-blue"],',
        '.mantine-ActionIcon-root[style*="mantine-color-violet"],',
        '.mantine-ThemeIcon-root[style*="mantine-color-cyan"],',
        '.mantine-ThemeIcon-root[style*="mantine-color-blue"],',
        '.mantine-ThemeIcon-root[style*="mantine-color-violet"] {',
        '  filter: drop-shadow(0 2px 5px rgba(var(--rwc-sub-accent-rgb), 0.18)) !important;',
        '}',
        '::selection { background: rgba(var(--rwc-sub-accent-rgb), 0.28); }',
        '* { scrollbar-color: rgba(var(--rwc-sub-accent-rgb), 0.42) transparent; }',
        '*::-webkit-scrollbar-thumb { background: rgba(var(--rwc-sub-accent-rgb), 0.34) !important; }',
        '*::-webkit-scrollbar-thumb:hover { background: rgba(var(--rwc-sub-accent-rgb), 0.52) !important; }',
    ])
    return '\n'.join(lines).strip() + '\n'


def effective_theme(config: dict) -> dict:
    data = ensure_config(config)
    if data.get('mode') == 'sync' and bool(config.get('theme', {}).get('enabled', True)):
        panel = config['theme']
        return {
            'accent': copy.deepcopy(panel['accent']),
            'background': copy.deepcopy(panel['background']),
            'surface': copy.deepcopy(panel['surface']),
            'radius': panel.get('radius', 'medium'),
        }
    return {
        'accent': copy.deepcopy(data['accent']),
        'background': copy.deepcopy(data['background']),
        'surface': copy.deepcopy(data['surface']),
        'radius': data.get('radius', 'medium'),
    }


def write_css(config: dict) -> Path:
    RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
    path = RUNTIME_DIR / 'subpage.css'
    path.write_text(render_css(effective_theme(config)), encoding='utf-8')
    os.chmod(path, 0o644)
    return path


def write_empty_css() -> Path:
    RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
    path = RUNTIME_DIR / 'subpage.css'
    path.write_text('/* Subscription Page Customizer disabled */\n', encoding='utf-8')
    os.chmod(path, 0o644)
    return path


def _route_proxy_info(config: dict):
    data = ensure_config(config).get('route') or {}
    if data.get('config_path'):
        return proxy.ProxyInfo(
            str(data.get('kind') or 'unknown'),
            str(data.get('name') or 'Proxy'),
            Path(str(data['config_path'])),
            Path(str(data.get('compose_dir') or Path(str(data['config_path'])).parent)),
            str(data.get('service') or ''),
        )
    return proxy.proxy_from_config(config) or proxy.detect_proxy()


def _find_original_target(text: str) -> str | None:
    for target in SUBPAGE_TARGETS:
        if target in text:
            return target
    return None


def patch_route(config: dict) -> None:
    ok, reason = local_status()
    if not ok:
        raise CommandError(f'Local Subscription Page unavailable: {reason}')

    info = _route_proxy_info(config)
    if not info or not info.config_path.exists():
        raise CommandError('Reverse proxy config for local Subscription Page was not found')

    text = info.config_path.read_text(encoding='utf-8')
    data = ensure_config(config)
    if SUBPAGE_CUSTOM_TARGET in text:
        route = data.setdefault('route', {})
        route.update({
            'kind': info.kind,
            'name': info.name,
            'config_path': str(info.config_path),
            'compose_dir': str(info.compose_dir),
            'service': info.service,
        })
        route.setdefault('original_target', SUBPAGE_UPSTREAM)
        save_config(config)
        return

    original = _find_original_target(text)
    if not original:
        raise CommandError(
            'Local Subscription Page upstream was not found in the reverse proxy config '
            f'(expected {SUBPAGE_UPSTREAM})'
        )

    backup = proxy._backup_proxy(info, text)
    patched = text.replace(original, SUBPAGE_CUSTOM_TARGET)
    try:
        proxy._apply_proxy_text(info, patched)
    except Exception:
        try:
            proxy._apply_proxy_text(info, text)
        except Exception:
            pass
        raise

    data['route'] = {
        'kind': info.kind,
        'name': info.name,
        'config_path': str(info.config_path),
        'compose_dir': str(info.compose_dir),
        'service': info.service,
        'original_target': original,
        'backup': str(backup),
    }
    save_config(config)


def restore_route(config: dict) -> bool:
    data = ensure_config(config)
    info = _route_proxy_info(config)
    if not info or not info.config_path.exists():
        data['route'] = {}
        save_config(config)
        return False

    text = info.config_path.read_text(encoding='utf-8')
    if SUBPAGE_CUSTOM_TARGET not in text:
        data['route'] = {}
        save_config(config)
        return False

    original = str((data.get('route') or {}).get('original_target') or SUBPAGE_UPSTREAM)
    restored = text.replace(SUBPAGE_CUSTOM_TARGET, original)
    try:
        proxy._apply_proxy_text(info, restored)
    except Exception:
        try:
            proxy._apply_proxy_text(info, text)
        except Exception:
            pass
        raise
    data['route'] = {}
    save_config(config)
    return True


def apply(config: dict) -> None:
    ok, reason = local_status()
    if not ok:
        raise CommandError(f'Local Subscription Page unavailable: {reason}')

    data = ensure_config(config)
    data['enabled'] = True

    # Rebuild the shared internal proxy without touching the official Panel or
    # Subscription Page containers. Panel can remain stock/direct while Sub Page
    # alone uses port 3101.
    proxy.write_runtime(config['theme'])
    write_css(config)
    proxy.start_injector()
    patch_route(config)
    save_config(config)


def reset(config: dict, *, keep_sync: bool = False) -> None:
    data = ensure_config(config)
    restore_route(config)
    data = ensure_config(config)
    data['enabled'] = False
    if not keep_sync:
        data['mode'] = 'custom'
    write_empty_css()
    save_config(config)

    # Keep the internal proxy only when Panel itself still uses it.
    if not bool(config.get('theme', {}).get('enabled', True)):
        proxy.stop_injector(remove=True)


def sync_with_panel(config: dict) -> None:
    data = ensure_config(config)
    data['mode'] = 'sync'
    panel = config.get('theme') or {}
    for field in ('accent', 'background', 'surface', 'radius'):
        if field in panel:
            data[field] = copy.deepcopy(panel[field])
    save_config(config)

    if not bool(panel.get('enabled', True)):
        reset(config, keep_sync=True)
        return
    apply(config)


def sync_if_needed(config: dict) -> None:
    data = ensure_config(config)
    if data.get('mode') != 'sync':
        return
    ok, _ = local_status()
    if not ok:
        return
    sync_with_panel(config)


def set_custom(config: dict, field: str, value) -> None:
    data = ensure_config(config)
    data[field] = list(value) if isinstance(value, tuple) else value
    data['mode'] = 'custom'
    data['enabled'] = True
    data['preset'] = 'custom'
    save_config(config)
